import type { Metadata } from "next";
import Link from "next/link";
import { LegalShell, Section, Bullets } from "../legal/legal-shell";

export const metadata: Metadata = {
  title: "Terms of Service — Genalot",
  description: "The terms governing your use of Genalot.",
};

export default function TermsPage() {
  return (
    <LegalShell
      title="Terms of Service"
      updated="5 July 2026"
      active="/terms"
      intro="These Terms of Service (the “Terms”) form a binding agreement between you and Genalot (“Genalot”, “we”, “us”, or “our”) and govern your access to and use of the Genalot website at genalot.com, our applications, and all related tools, features, and services (together, the “Service”). Please read these Terms carefully. By creating an account, purchasing a plan or credits, or otherwise using the Service, you agree to be bound by these Terms. If you do not agree, you must not use the Service."
    >
      <Section n="1" title="Definitions">
        <Bullets
          items={[
            <><strong className="text-white/80">&ldquo;Account&rdquo;</strong> — the registered account you create to access the Service.</>,
            <><strong className="text-white/80">&ldquo;Credits&rdquo;</strong> — the prepaid units, included with a plan or bought as a pack, consumed when you generate content.</>,
            <><strong className="text-white/80">&ldquo;Inputs&rdquo;</strong> — the prompts, text, images, reference material, and other content you submit to the Service.</>,
            <><strong className="text-white/80">&ldquo;Outputs&rdquo;</strong> — the images, videos, and other content generated by the Service in response to your Inputs.</>,
            <><strong className="text-white/80">&ldquo;User Content&rdquo;</strong> — collectively, your Inputs and Outputs and any content you upload, store, or publish through the Service.</>,
          ]}
        />
      </Section>

      <Section n="2" title="Eligibility and accounts">
        <p>
          You must be at least 18 years old, or the age of majority in your jurisdiction, and able to
          form a binding contract to use the Service. By using the Service you represent that you meet
          these requirements and that all registration information you provide is accurate and kept
          current.
        </p>
        <p>
          You are responsible for safeguarding your Account credentials and for all activity that
          occurs under your Account. You must notify us immediately of any unauthorised use. We are
          not liable for any loss arising from your failure to protect your credentials. If you create
          an Account on behalf of a business, you represent that you are authorised to bind that
          business to these Terms.
        </p>
      </Section>

      <Section n="3" title="The Service">
        <p>
          Genalot is an AI-powered content-creation platform that lets you generate images, video,
          advertisements, and related media from prompts and reference material, and to schedule and
          publish that content to connected social-media channels. The Service orchestrates
          third-party AI models and other providers to produce Outputs. Features, models, limits, and
          pricing may change, be added, or be removed over time as the Service evolves.
        </p>
      </Section>

      <Section n="4" title="Credits, plans, and billing">
        <p>
          Access to generation features requires Credits, provided through a subscription plan or a
          one-off credit pack. Each generation consumes Credits according to the model, resolution,
          duration, and options selected. Prices are displayed at checkout and are billed through our
          third-party payment provider.
        </p>
        <Bullets
          items={[
            "Subscription plans renew automatically each billing period until cancelled. You may cancel at any time from your billing settings to stop future renewals.",
            "Credit packs are one-off purchases and, unless stated otherwise, expire after the period shown at purchase; expired credits are forfeited.",
            "You authorise us and our payment provider to charge your payment method for all fees incurred, including recurring subscription fees.",
            "You are responsible for any taxes associated with your purchases, except taxes on our net income.",
          ]}
        />
        <p>
          Refunds are governed by our{" "}
          <Link href="/refund" className="text-primary/70 hover:text-primary">Refund Policy</Link>, which forms part of these Terms.
        </p>
      </Section>

      <Section n="5" title="Acceptable use">
        <p>You agree not to use the Service, and not to create, upload, generate, or distribute any content, to:</p>
        <Bullets
          items={[
            "Violate any law or regulation, or infringe the intellectual-property, privacy, publicity, or other rights of any person.",
            "Create sexual content involving minors, or any child sexual abuse material — this is strictly prohibited and will be reported to the authorities.",
            "Generate non-consensual intimate imagery, or deepfakes or impersonations of real people intended to deceive, defame, harass, or defraud.",
            "Produce content that is hateful, harassing, threatening, or that incites violence or discrimination against individuals or groups.",
            "Create disinformation, fraudulent, or deceptive material, including impersonating a person or entity or misrepresenting your affiliation.",
            "Depict a real, identifiable person without a lawful basis, or use a person's likeness in a way that violates their rights.",
            "Attempt to bypass usage limits, Credits, or safety systems; reverse engineer, scrape, or resell the Service; or introduce malware or overload our systems.",
            "Use the Service to build a competing product, or to train, fine-tune, or improve a competing machine-learning model.",
          ]}
        />
        <p>
          You are solely responsible for your Inputs and for how you use your Outputs, including
          obtaining any rights, licences, consents, or releases required for the reference material
          you submit and for the manner in which you publish or distribute Outputs. We may use
          automated and manual review to enforce this section and may remove content or suspend
          Accounts that violate it.
        </p>
      </Section>

      <Section n="6" title="Your content and ownership">
        <p>
          As between you and Genalot, you retain all rights you hold in your Inputs, and, to the
          extent permitted by law and by the terms of the underlying AI providers, we assign to you
          our rights, title, and interest in the Outputs you generate. You are responsible for
          ensuring you have the rights to your Inputs and that your use of Outputs is lawful.
        </p>
        <p>
          You grant Genalot a worldwide, non-exclusive, royalty-free licence to host, store, process,
          reproduce, and transmit your User Content solely to operate, secure, and improve the
          Service, to deliver features you request (such as publishing to a connected channel), and as
          otherwise described in our{" "}
          <Link href="/privacy" className="text-primary/70 hover:text-primary">Privacy Policy</Link>. You may
          delete your User Content at any time, subject to reasonable technical and backup retention.
        </p>
      </Section>

      <Section n="7" title="AI-generated content — important disclaimers">
        <Bullets
          items={[
            "Outputs are generated by probabilistic AI models and may be inaccurate, may not be unique, and may in some cases resemble existing works or the outputs produced for other users. We do not warrant that Outputs are original, non-infringing, or fit for any particular purpose.",
            "The legal status of ownership and copyright in AI-generated content varies by jurisdiction and is still developing. You are responsible for determining whether your intended use of an Output is lawful in your jurisdiction.",
            "Outputs may reflect biases or limitations of the underlying models. You must review Outputs before relying on or publishing them, and you assume all risk arising from their use.",
            "You must not present AI-generated content in a way that is deceptive or that breaches the rules of any platform on which you publish it.",
          ]}
        />
      </Section>

      <Section n="8" title="Third-party services and social publishing">
        <p>
          The Service relies on third-party providers, including AI-model providers, hosting,
          payment, email, and social-media distribution partners. Your use of features that connect to
          third-party platforms (for example, scheduling or auto-posting to a social network) is also
          subject to those platforms&rsquo; own terms. You authorise us and our distribution partner
          to publish content to the channels you connect, and you are responsible for complying with
          each platform&rsquo;s policies. We are not responsible for the acts, omissions, or
          availability of third-party services.
        </p>
      </Section>

      <Section n="9" title="Intellectual property in the Service">
        <p>
          The Service, including its software, design, branding, logos, and content we create
          (excluding your User Content), is owned by Genalot or its licensors and is protected by
          intellectual-property laws. We grant you a limited, non-exclusive, non-transferable,
          revocable licence to use the Service in accordance with these Terms. No rights are granted
          except as expressly stated.
        </p>
      </Section>

      <Section n="10" title="Suspension and termination">
        <p>
          You may stop using the Service and close your Account at any time. We may suspend or
          terminate your access, with or without notice, if we reasonably believe you have violated
          these Terms, created risk or legal exposure for us, or engaged in fraudulent or abusive
          behaviour. On termination, your right to use the Service ends; sections that by their nature
          should survive (including ownership, disclaimers, limitation of liability, and
          indemnification) will survive.
        </p>
      </Section>

      <Section n="11" title="Disclaimers of warranties">
        <p>
          The Service is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without
          warranties of any kind, whether express, implied, or statutory, including implied warranties
          of merchantability, fitness for a particular purpose, title, and non-infringement. We do not
          warrant that the Service will be uninterrupted, error-free, secure, or that Outputs will
          meet your expectations. Some jurisdictions do not allow the exclusion of certain warranties,
          so some of the above may not apply to you.
        </p>
      </Section>

      <Section n="12" title="Limitation of liability">
        <p>
          To the maximum extent permitted by law, Genalot and its officers, employees, and suppliers
          will not be liable for any indirect, incidental, special, consequential, exemplary, or
          punitive damages, or for any loss of profits, revenue, data, goodwill, or business, arising
          out of or related to your use of (or inability to use) the Service, even if advised of the
          possibility of such damages. To the maximum extent permitted by law, our total aggregate
          liability for all claims relating to the Service will not exceed the greater of (a) the
          amount you paid to us in the three months before the event giving rise to the claim, or
          (b) USD 50. These limitations do not exclude liability that cannot be excluded under
          applicable law.
        </p>
      </Section>

      <Section n="13" title="Indemnification">
        <p>
          You agree to indemnify and hold harmless Genalot and its affiliates from and against any
          claims, liabilities, damages, losses, and expenses (including reasonable legal fees) arising
          out of or related to your Inputs or Outputs, your use of the Service, your violation of
          these Terms, or your infringement of any third-party right.
        </p>
      </Section>

      <Section n="14" title="Changes to the Service and these Terms">
        <p>
          We may modify the Service or these Terms from time to time. If we make material changes to
          these Terms, we will update the &ldquo;Last updated&rdquo; date and, where appropriate,
          provide additional notice. Your continued use of the Service after changes take effect
          constitutes acceptance of the revised Terms. If you do not agree to the changes, you must
          stop using the Service.
        </p>
      </Section>

      <Section n="15" title="Governing law and disputes">
        <p>
          These Terms are governed by the laws of the Republic of South Africa, without regard to its
          conflict-of-laws rules, unless a mandatory law of your country of residence requires
          otherwise. You agree that the courts located in South Africa will have jurisdiction over any
          dispute arising from these Terms, subject to any non-waivable right you have to bring
          proceedings in your local courts. Before commencing any formal proceeding, you agree to
          first contact us to seek a good-faith resolution.
        </p>
      </Section>

      <Section n="16" title="General">
        <Bullets
          items={[
            "These Terms, together with the Privacy Policy and Refund Policy, are the entire agreement between you and us regarding the Service.",
            "If any provision is found unenforceable, the remaining provisions remain in full force.",
            "Our failure to enforce a right is not a waiver of that right.",
            "You may not assign these Terms without our consent; we may assign them in connection with a merger, acquisition, or sale of assets.",
            "We are not liable for any delay or failure to perform caused by events beyond our reasonable control (force majeure).",
          ]}
        />
      </Section>

      <Section n="17" title="Contact">
        <p>
          Questions about these Terms may be sent to{" "}
          <a href="mailto:support@genalot.com" className="text-primary/70 hover:text-primary">support@genalot.com</a>.
        </p>
      </Section>
    </LegalShell>
  );
}
