// Service-role Supabase client + queue/credit helpers for the worker.
// Service role bypasses RLS — the worker is a trusted backend process.
import { createClient } from "@supabase/supabase-js";

const url = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const key = process.env.SUPABASE_SERVICE_ROLE_KEY!;

export const BUCKET = "ad-studio";
export const admin = createClient(url, key, { auth: { persistSession: false } });
export const pub = (p: string) => admin.storage.from(BUCKET).getPublicUrl(p).data.publicUrl;

export type Job = {
  id: string;
  account_id: string;
  created_by: string | null;
  type: string; // 'image' | 'video' | 'ugc'
  brief: Record<string, unknown> | null;
  format: string | null;
  estimated_credits: number | null;
};

// Atomically claim the next queued job (SKIP LOCKED + per-account cap) via the
// migration's claim_ad_job(). Returns null when the queue is empty.
export async function claimJob(worker: string, maxPerAccount = 2): Promise<Job | null> {
  const { data, error } = await admin.rpc("claim_ad_job", {
    worker,
    max_per_account: maxPerAccount,
  });
  if (error) {
    console.error("[worker] claim error:", error.message);
    return null;
  }
  return Array.isArray(data) && data[0] ? (data[0] as Job) : null;
}

export async function setProgress(id: string, progress: string): Promise<void> {
  await admin.from("ad_jobs").update({ progress, updated_at: new Date().toISOString() }).eq("id", id);
}

// Mark done + true-up credits (refund estimate − actual).
export async function settle(id: string, actualCredits: number): Promise<void> {
  const { error } = await admin.rpc("settle_ad_job", { jid: id, actual: Math.max(0, Math.round(actualCredits)) });
  if (error) console.error("[worker] settle error:", error.message);
}

// Mark failed + full refund.
export async function refund(id: string, err: string): Promise<void> {
  const { error } = await admin.rpc("refund_ad_job", { jid: id, err: err.slice(0, 500) });
  if (error) console.error("[worker] refund error:", error.message);
}

export async function requeueStale(staleMinutes = 15): Promise<number> {
  const { data, error } = await admin.rpc("requeue_stale_ad_jobs", { stale_minutes: staleMinutes });
  if (error) {
    console.error("[worker] reaper error:", error.message);
    return 0;
  }
  return (data as number) ?? 0;
}

// Upload generated bytes to the outputs path and return the stored storage_path.
export async function uploadOutput(
  accountId: string,
  jobId: string,
  idx: number,
  bytes: Uint8Array,
  contentType: string,
  ext: string,
): Promise<string | null> {
  const path = `outputs/${accountId}/${jobId}/${idx}.${ext}`;
  const up = await admin.storage.from(BUCKET).upload(path, bytes, { contentType, upsert: true });
  return up.error ? null : path;
}

// Insert an ad_assets row attached to the (already-claimed) job.
export async function insertAsset(
  job: Job,
  o: { type: "image" | "video"; storagePath: string; variationIndex: number; metadata: Record<string, unknown> },
): Promise<string | null> {
  const { data, error } = await admin
    .from("ad_assets")
    .insert({
      account_id: job.account_id,
      job_id: job.id,
      type: o.type,
      storage_path: o.storagePath,
      variation_index: o.variationIndex,
      metadata: o.metadata,
    })
    .select("id")
    .single();
  if (error) {
    console.error("[worker] insertAsset error:", error.message);
    return null;
  }
  return data!.id as string;
}

// Resolve @-referenced Soul IDs (explicit ids + @handles typed in the prompt),
// mirroring the route. Returns chosen souls + a name map for prompt cleanup.
export async function resolveSouls(
  accountId: string,
  soulIds: string[],
  prompt: string,
): Promise<{
  chosen: Array<{ handle: string; name: string; kind: string; url: string }>;
  nameByHandle: Record<string, string>;
}> {
  const handleMatches = [...prompt.matchAll(/@([a-zA-Z0-9_-]+)/g)].map((m) => m[1].toLowerCase());
  if (!soulIds.length && !handleMatches.length) return { chosen: [], nameByHandle: {} };
  const { data } = await admin
    .from("ad_soul_ids")
    .select("id, handle, name, kind, storage_path")
    .eq("account_id", accountId);
  const nameByHandle: Record<string, string> = {};
  for (const s of data ?? []) nameByHandle[String(s.handle).toLowerCase()] = String(s.name);
  const chosen = (data ?? [])
    .filter(
      (s) => soulIds.includes(s.id as string) || handleMatches.includes(String(s.handle).toLowerCase()),
    )
    .slice(0, 9)
    .map((s) => ({
      handle: String(s.handle).toLowerCase(),
      name: String(s.name),
      kind: String(s.kind),
      url: pub(s.storage_path as string),
    }));
  return { chosen, nameByHandle };
}
